DROP TABLE IF EXISTS "PERMISO_ROL";
DROP TABLE IF EXISTS "PERMISO";
DROP TABLE IF EXISTS "ROL";

DROP TABLE IF EXISTS "INCIDENCIA_ESTADO";
DROP TABLE IF EXISTS "INCIDENCIA_ESTAMENTO";
DROP TABLE IF EXISTS "INCIDENCIA_INFRACTOR_FORANEO";

DROP TABLE IF EXISTS "COORDENADA";
DROP TABLE IF EXISTS "ZONA";
DROP TABLE IF EXISTS "SANCION";

DROP TABLE IF EXISTS "INFRACTOR_FORANEO";

DROP TABLE IF EXISTS "DENUNCIA_MEDIA";
DROP TABLE IF EXISTS "INCIDENCIA_MEDIA";

DROP TABLE IF EXISTS "INCIDENCIA";
DROP TABLE IF EXISTS "DENUNCIA";
DROP TABLE IF EXISTS "TIPO";
DROP TABLE IF EXISTS "CATEGORIA_DENUNCIA";
DROP TABLE IF EXISTS "ESTADO";
DROP TABLE IF EXISTS "CATEGORIA_INCIDENCIA";
DROP TABLE IF EXISTS "TIPO_SANCION";
DROP TABLE IF EXISTS "ESTAMENTO";
DROP TABLE IF EXISTS "TIPO_ESTAMENTO";
DROP TABLE IF EXISTS "OPERATIVO";
DROP TABLE IF EXISTS "USUARIO";
DROP TABLE IF EXISTS "FACULTAD";
